config/routes.rb
Rails.application.routes.draw do
  devise_for :managers, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :flats

  resources :posts

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/flat.rb
class Flat < ActiveRecord::Base
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < InheritedResources::Base

  private

    def flat_params
      params.require(:flat).permit(:Name, :Address, :RentalDate, :Occupied)
    end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base

  private

    def post_params
      params.require(:post).permit(:Name, :Description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/flats/_form.html.erb
<%= form_for(@flat) do |f| %>
  <% if @flat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

      <ul>
      <% @flat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Address %><br>
    <%= f.text_area :Address %>
  </div>
  <div class="field">
    <%= f.label :RentalDate %><br>
    <%= f.date_select :RentalDate %>
  </div>
  <div class="field">
    <%= f.label :Occupied %><br>
    <%= f.check_box :Occupied %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing flat</h1>

<%= render 'form' %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<div class="row">
        <div class="large-3 columns">
          <h1><img src="http://placehold.it/400x100&text=Logo"></h1>
        </div>
        <div class="large-9 columns">
          <ul class="button-group right">
            <li><a href="/" class="button">Home</a></li>
            <li><a href="/posts" class="button">Posts</a></li>
            <li><a href="/flats" class="button">Flats</a></li>
            <li><a href="/users/register" class="button">Register</a></li>
          </ul>
        </div>
      </div>
<div class="row">
<h1>Listing flats</h1>
<div class="large-3 columns ">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Rentaldate</th>
      <th>Occupied</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flats.each do |flat| %>
      <tr>
        <td><%= flat.Name %></td>
        <td><%= flat.Address %></td>
        <td><%= flat.RentalDate %></td>
        <td><%= flat.Occupied %></td>
        <td><%= link_to 'Show', flat %></td>
        <td><%= link_to 'Edit', edit_flat_path(flat) %></td>
        <td><%= link_to 'Destroy', flat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<center><div class="button"><%= link_to 'New Flat', new_flat_path %></div></center>
<footer class="row">
        <div class="large-12 columns">
          <hr/>
          <div class="row">
            <div class="large-6 columns">
              <p>© Copyright no one at all.</p>
            </div>
            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="/" class="button">Home</a></li>
            <li><a href="/posts" class="button">Posts</a></li>
            <li><a href="/flats" class="button">Flats</a></li>
            <li><a href="/users/register" class="button">Register</a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render 'form' %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flat.Name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @flat.Address %>
</p>

<p>
  <strong>Rentaldate:</strong>
  <%= @flat.RentalDate %>
</p>

<p>
  <strong>Occupied:</strong>
  <%= @flat.Occupied %>
</p>

<%= link_to 'Edit', edit_flat_path(@flat) %> |
<%= link_to 'Back', flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="row">
        <div class="large-3 columns">
          <h1><img src="http://placehold.it/400x100&text=Logo"></h1>
        </div>
        <div class="large-9 columns">
          <ul class="button-group right">
            <li><a href="/" class="button">Home</a></li>
            <li><a href="/posts" class="button">Posts</a></li>
            <li><a href="/flats" class="button">Flats</a></li>
            <li><a href="/users/register" class="button">Register</a></li>
          </ul>
        </div>
      </div>
<div class="row">
<h1>Listing posts</h1>
<div class="large-3 columns ">
          
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.Name %></td>
        <td><%= post.Description %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

</div>
<center><div class="button"><%= link_to 'New Post', new_post_path %></div></center>

<footer class="row">
        <div class="large-12 columns">
          <hr/>
          <div class="row">
            <div class="large-6 columns">
              <p>© Copyright no one at all.</p>
            </div>
            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="/" class="button">Home</a></li>
            <li><a href="/posts" class="button">Posts</a></li>
            <li><a href="/flats" class="button">Flats</a></li>
            <li><a href="/users/register" class="button">Register</a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.Name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.Description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
       
   
      <div class="row">
        <div class="large-3 columns">
          <h1><img src="http://placehold.it/400x100&text=Logo"></h1>
        </div>
        <div class="large-9 columns">
          <ul class="button-group right">
            <li><a href="/" class="button">Home</a></li>
            <li><a href="/posts" class="button">Posts</a></li>
            <li><a href="/flats" class="button">Flats</a></li>
            <li><a href="/users/register" class="button">Register</a></li>
          </ul>
        </div>
      </div>
     
       
     
     
       
     
      <div class="row">
        <div class="large-12 columns">
          <img src="http://placehold.it/1000x400&text=[img]">
     
          <hr>
        </div>
      </div>
       
     
      <div class="row">
        <div class="large-4 columns">
          <img src="http://placehold.it/400x300&text=[img]">
        </div>
        <div class="large-8 columns">
          <h4>New way to Manage Socities.</h4>
          <div class="row">
            <div class="large-6 columns">
              <p>We do different things in same and sane way.</p>
            </div>
            <div class="large-6 columns">
              <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
            </div>
          </div>
        </div>
      </div>
     
     
       
     
      <div class="row">
        <div class="large-8 columns">
          <h4>This is a content section.</h4>
     
          <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
     
          <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
     
        </div>
        <div class="large-4 columns">
          <img src="http://placehold.it/400x300&text=[img]">
        </div>
      </div>
    
       
     
      <footer class="row">
        <div class="large-12 columns">
          <hr/>
          <div class="row">
            <div class="large-6 columns">
              <p>© Copyright no one at all.</p>
            </div>
            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="/" class="button">Home</a></li>
            <li><a href="/posts" class="button">Posts</a></li>
            <li><a href="/flats" class="button">Flats</a></li>
            <li><a href="/users/register" class="button">Register</a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    